# Generated by Django 5.1.3 on 2024-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_user_city_alter_user_country_alter_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menuPdf',
            field=models.FileField(blank=True, null=True, upload_to='menu_pdfs/'),
        ),
    ]
