# Generated by Django 5.1.3 on 2024-11-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_alter_menu_menu_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietaryrestriction',
            old_name='description',
            new_name='name',
        ),
    ]
