# Generated by Django 5.1.3 on 2024-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_rename_description_dietaryrestriction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
