# Generated by Django 5.1.3 on 2024-11-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_alter_menu_menu_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuversion',
            name='post',
        ),
        migrations.AlterField(
            model_name='menuversion',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.restaurant'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
