# Generated by Django 5.1.3 on 2024-11-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0014_rename_action_auditlog_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
