# Generated by Django 5.1.3 on 2024-11-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0015_remove_restaurant_opening_hours_delete_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_version',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='menu_version',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='city',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='country',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='state',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='street',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='zip',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.restaurant'),
        ),
        migrations.AddField(
            model_name='menu',
            name='timeUpload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MenuVersion',
        ),
    ]
