# Generated by Django 5.1.3 on 2024-11-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0016_alter_menu_menu_version_remove_auditlog_menu_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_version',
        ),
        migrations.CreateModel(
            name='MenuVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(editable=False)),
                ('composite_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='menu_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menuversion'),
        ),
        migrations.AddField(
            model_name='menu',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menuversion'),
        ),
    ]
