# Generated by Django 5.1.3 on 2024-11-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0017_remove_auditlog_menu_remove_menu_menu_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuversion',
            options={'verbose_name': 'Menu Versions', 'verbose_name_plural': 'Menu Versions'},
        ),
    ]
