# Generated by Django 5.1.3 on 2024-11-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0018_alter_menuversion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(blank=True, default='temp', null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.restaurant'),
        ),
    ]
