# Generated by Django 5.1.3 on 2024-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0020_alter_menu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, default='temp', max_length=50, null=True),
        ),
    ]
